# Generated by Django 4.2.20 on 2025-03-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0003_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
