version: '3'

services:
  backend:
    image: registry.cn-hongkong.aliyuncs.com/tongihttigerbreak/tigerhouse:backend-latest
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - DEBUG=False
    depends_on:
      - db
      - redis

  frontend:
    image: registry.cn-hongkong.aliyuncs.com/tongihttigerbreak/tigerhouse:frontend-latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=knowledge_graph
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: 