# 数据库服务配置文件
# Last updated: 2024-01-09 15:45
version: '3.8'

# Neo4j 相关配置变量 - 部署时可能需要修改
x-neo4j-variables: &neo4j-variables
  NEO4J_USER: neo4j  # Neo4j 用户名
  NEO4J_PASSWORD: root123321  # Neo4j 密码，部署时建议修改
  NEO4J_URI: bolt://myproject-neo4j-1:7687  # Neo4j 连接地址，注意容器名要匹配
  NEO4J_AUTH: neo4j/root123321  # 认证信息，格式为 username/password，需要与上面的密码保持一致

# MySQL 相关配置变量 - 部署时可能需要修改
x-mysql-variables: &mysql-variables
  MYSQL_DATABASE: knowledge_graph  # 数据库名称
  MYSQL_ROOT_PASSWORD: 123456  # Root 密码，部署时建议修改
  MYSQL_HOST: myproject-mysql-1  # MySQL 主机名，注意容器名要匹配
  MYSQL_PORT: 3306  # MySQL 端口号

services:
  neo4j:
    image: neo4j:4.4  # Neo4j 版本，可根据需要修改
    container_name: myproject-neo4j-1  # Neo4j 容器名，修改时需要同步修改 NEO4J_URI
    ports:
      - "7474:7474"  # Neo4j HTTP 端口
      - "7687:7687"  # Neo4j Bolt 端口
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH:-neo4j/root123321}
    volumes:
      - neo4j_data:/data  # 数据持久化
      - neo4j_logs:/logs  # 日志持久化
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "http://localhost:7474", "-O", "/dev/null"]
    restart: unless-stopped

  mysql:
    image: mysql:8.0  # MySQL 版本，可根据需要修改
    container_name: myproject-mysql-1  # MySQL 容器名，修改时需要同步修改 MYSQL_HOST
    ports:
      - "3307:3306"  # MySQL 端口，外部访问使用 3307
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-knowledge_graph}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
    volumes:
      - mysql_data:/var/lib/mysql  # 数据持久化
      - mysql_tmp:/tmp  # 临时文件目录
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

# 网络配置
networks:
  app-network:
    driver: bridge

# 数据卷配置 - 确保数据持久化
volumes:
  neo4j_data:  # Neo4j 数据持久化
  neo4j_logs:  # Neo4j 日志持久化
  mysql_data:  # MySQL 数据持久化
  mysql_tmp:   # MySQL 临时文件目录 