name: Deploy to Production

on:
  push:
    branches:
      - main
      - master
      - release/*
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'docker/**'
      - 'deploy/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:  # 保留手动触发选项

env:
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
  PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
  DB_SERVER_IP: ${{ secrets.DB_SERVER_IP }}  # 添加数据库服务器IP
  # 阿里云容器镜像服务配置
  ALIYUN_REGISTRY: registry.cn-hongkong.aliyuncs.com
  ALIYUN_NAMESPACE: tongihttigerbreak
  ALIYUN_REPOSITORY: tigerhouse

jobs:
  init-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Execute init-server.sh
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
          DB_SERVER_IP: ${{ secrets.DB_SERVER_IP }}  # 添加数据库服务器IP
        run: |
          chmod +x ./deploy/init-server.sh
          ./deploy/init-server.sh
      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync sshpass
      - name: Check Docker directory
        run: |
          echo "=== 检查本地 Docker 目录 ==="
          if [ ! -d "docker" ]; then
            echo "❌ 错误: docker 目录不存在"
            exit 1
          fi
          if [ ! -f "docker/docker-compose.yml" ]; then
            echo "❌ 错误: docker/docker-compose.yml 文件不存在"
            exit 1
          fi
          echo "本地 Docker 目录内容:"
          ls -la docker/
          echo "✅ 本地 Docker 目录检查完成"
      - name: Copy Docker directory to server
        run: |
          echo "=== 开始复制 Docker 目录到服务器 ==="
          # 显示本地文件内容
          echo "本地 docker-compose.yml 内容:"
          cat docker/docker-compose.yml
          
          # 复制文件
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no" docker/ "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/root/${{ secrets.PROJECT_NAME }}/docker/"
          
          # 显示服务器文件内容
          echo "服务器 docker-compose.yml 内容:"
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}" "cat /root/${{ secrets.PROJECT_NAME }}/docker/docker-compose.yml"
          
          echo "✅ Docker 目录复制完成"
      - name: Verify Docker directory on server
        run: |
          echo "=== 验证服务器上的 Docker 目录 ==="
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}" "echo '服务器 Docker 目录内容:'; ls -la /root/${{ secrets.PROJECT_NAME }}/docker/"
          echo "✅ 服务器 Docker 目录验证完成"

  build-images:
    needs: init-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/backend.Dockerfile
          push: true
          tags: |
            ${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAMESPACE }}/${{ env.ALIYUN_REPOSITORY }}:backend-latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: docker/frontend.Dockerfile
          push: true
          tags: |
            ${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAMESPACE }}/${{ env.ALIYUN_REPOSITORY }}:frontend-latest

  deploy:
    needs: build-images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Execute deploy.sh
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
          ALIYUN_REPOSITORY: ${{ env.ALIYUN_REPOSITORY }}
          ALIYUN_USERNAME: ${{ secrets.ALIYUN_USERNAME }}
          ALIYUN_PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}
          DB_SERVER_IP: ${{ secrets.DB_SERVER_IP }}  # 添加数据库服务器IP
        run: |
          chmod +x ./deploy/deploy.sh
          ./deploy/deploy.sh
      - name: Notify on success
        if: success()
        run: |
          echo "Deployment completed successfully!"
      - name: Notify on failure
        if: failure()
        run: |
          echo "Deployment failed!" 